version: "3"
services:
  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: jpr
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  backend:
    image: fpr-backend:dev-env-test
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      spring.datasource.url: jdbc:postgresql://database:5432/jpr