spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: com.esgi.infrastructure.persistence.strategies.PhysicalStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/jpr?schema=public
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  devtools:
    livereload:
      port: 35730
security:
  # minimum 256 bits
  key: 12345678901234567890123456789012

server:
  forward-headers-strategy: framework