spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: com.esgi.infrastructure.persistence.strategies.PhysicalStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    open-in-view: false
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/jpr?schema=public
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  devtools:
    livereload:
      port: 35730
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
security:
  # minimum 256 bits
  key: 12345678901234567890123456789012

server:
  forward-headers-strategy: framework

games-bucket:
  name: game-uploads20230717200505738400000001

medias-bucket:
  name: fpr-medias20230717200506511900000003

aws:
  region: eu-west-3
  accountId: test